version: 2

updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "zubinqayam"
    assignees:
      - "zubinqayam"
    labels:
      - "dependencies"
      - "security"
      - "automation"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"

  # Monitor npm dependencies if package.json exists
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
    open-pull-requests-limit: 10
    reviewers:
      - "zubinqayam"
    assignees:
      - "zubinqayam"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"
    # Group updates for better PR management
    groups:
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "@types/*"
          - "eslint*"
          - "prettier*"
          - "*-dev"
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security"

  # Monitor Docker dependencies if Dockerfile exists
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "zubinqayam"
    assignees:
      - "zubinqayam"
    labels:
      - "dependencies"
      - "security"
      - "docker"
    commit-message:
      prefix: "chore(docker):"

  # Monitor pip dependencies if requirements.txt exists
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "10:00"
    open-pull-requests-limit: 5
    reviewers:
      - "zubinqayam"
    assignees:
      - "zubinqayam"
    labels:
      - "dependencies"
      - "security"
      - "python"
    commit-message:
      prefix: "chore(deps):"